let artistas = [
    {foto:"https://firebasestorage.googleapis.com/v0/b/canciones-7fc70.appspot.com/o/wendy-sulca-a-los-24___OfJmDWwVx_720x0__1.webp?alt=media&token=c87fec32-06c4-45c8-bbba-477ac2a102a6", historia:"Wendy Sulca Quispe (Lima, Perú, 22 de abril de 1996) es una cantante peruana de música andina y pop, conocida principalmente por su exposición mediática alcanzada por sus videos virales publicados en el sitio YouTube. Sulca nació en el distrito limeño de San Juan de Miraflores."},
    {foto:"https://firebasestorage.googleapis.com/v0/b/canciones-7fc70.appspot.com/o/charlie-zaa_1924345_20190717145204.jpg?alt=media&token=befe9354-6f04-48cd-8a48-64a4f1523456", historia:"Fue bautizado por sus padres con el nombre de Carlos Alberto Sánchez Ramírez. Su debut formal fue a los 16 años en la agrupación Alma de barrio con temas famosos como Tu indiferencia, también perteneciente a Jairo Varela, donde interpretó clásicos como Casualidad de la vida, Solo soy de ti, Puede ser y Primera vez."},
    {foto:"https://firebasestorage.googleapis.com/v0/b/canciones-7fc70.appspot.com/o/cuartetoperfil.jpg?alt=media&token=1b8a771c-ac41-4d9b-9d3d-7df9943870bc", historia:"Cuarteto de Nos nace a mediados de los 80 y en los 90 se consolida como una de las bandas más significativas del rock uruguayo. Irreverentes, con humor negro, música de todos los estilos, desafiantes y con una actitiud punk llevada al humor y a la creación de personajes extraños de ficción."},
    {foto:"https://firebasestorage.googleapis.com/v0/b/canciones-7fc70.appspot.com/o/Britney-Spears-en-los-Hollywood-Beauty-Awards-de-2018-f4cfcc.webp?alt=media&token=f7cc8595-efe1-458c-bdac-24e56507b236", historia:"Britney Jean Spears nació un 2 de diciembre de 1981 en Mississippi. Creció en Louisiana entre clases de baile y de gimnasia, y soñando con ser cantante. Dispuesta a lograrlo, con poco más de 10 años, se trasladó junto a su madre a Nueva York para protagonizar un espectáculo en el off-Broadway, Ruthless."},
    {foto:"https://firebasestorage.googleapis.com/v0/b/canciones-7fc70.appspot.com/o/delfin-hasta-el-fin-uno.jpeg?alt=media&token=93fbe872-a355-4110-8117-953d7311030a", historia:"Delfín Quishpe Apugllón nació el 28 de diciembre de 1978 en San Antonio de Encalado, Guamote, Ecuador. Es el último de cuatro hermanos, es por eso que sus padres le bautizaron con este nombre. Sus inicios como cantante fueron en su pueblo natal, cuando tenía 10 años"},
    {foto:"https://firebasestorage.googleapis.com/v0/b/canciones-7fc70.appspot.com/o/La-tigresa-del-Oriente.jpeg?alt=media&token=04ff32f2-78dc-47f1-b18d-2052030ddc31", historia:"La Tigresa del Oriente (22 de noviembre de 1944) cantante, actriz y maquilladora. Nació en Constancia, Maynas, Perú. Fue bautizada como Judith Bustos. Su padre se ganó la vida aprovechando la fiebre del caucho en la selva peruana."},
    {foto:"https://firebasestorage.googleapis.com/v0/b/canciones-7fc70.appspot.com/o/PORT%20TIGRES%20DEL%20NORTE%20single%20a%20mi%20gente%20de%20aca%CC%81.jpeg?alt=media&token=a78ad25e-a6ec-4330-b17d-9a5a6ffa4bc8", historia:"La historia de Los Tigres del Norte se inicia en Rosa Morada, sindicatura del municipio de Mocorito, estado de Sinaloa, México, en el año 1968, cuando Jorge, el mayor de la familia Hernández Angulo, convence a sus hermanos Raúl, Hernán y a su primo Óscar para formar un grupo. Por entonces Jorge sólo tenía 14 años."},
    {foto:"https://firebasestorage.googleapis.com/v0/b/canciones-7fc70.appspot.com/o/CETQGWDL4JB3FHU37MQNVUBFZQ.jpg?alt=media&token=732c17f1-f39a-46e6-8b33-670187521771", historia:"Nacida en el seno de una familia de clase media, Shakira era hija de William Mebarak, de ascendencia libanesa, y de Nidia Ripoll, colombiana con antepasados catalanes. Desde los cinco años mostró indicios de su vocación artística, demostrando su notable talento en la interpretación de danzas y cantos árabes."},
    {foto:"https://firebasestorage.googleapis.com/v0/b/canciones-7fc70.appspot.com/o/james-brown-656x368.jpg?alt=media&token=6e894116-3a57-41bf-bd03-b21415ecfb3b", historia:"James Joseph Brown (Barnwell, Carolina del Sur; 3 de mayo de 1933-Atlanta, Georgia; 25 de diciembre de 2006) fue un cantante de soul y funk estadounidense. Progenitor de la música funk y una figura importante de la música y la danza del siglo XX, a menudo se le refiere por los apodos honoríficos Padrino del Soul, Sr."},
    {foto:"", historia:"más conocido como Elvis Presley o simplemente Elvis, fue un cantante, compositor y actor estadounidense, considerado como uno de los iconos culturales más populares del siglo XX. Es apodado como «el rey del rock and roll». Nació en Tupelo, Misisipi, pero cuando tenía trece años, se mudó junto a su familia a Memphis, en Tennessee, donde en 1954 comenzó su carrera artística cuando el dueño de Sun Records, Sam Phillips, vio en él la manera de expandir la música afroamericana. Acompañado por el guitarrista Scotty Moore y el contrabajista Bill Black, fue uno de los creadores del rockabilly, un estilo de tempo rápido impulsado por un constante ritmo que consiste en una fusión de música country y rhythm and blues."},
]